import type { LucideIcon } from "lucide-react";
import {
  ArrowUp,
  Bell,
  BookOpen,
  Bookmark,
  Bot,
  Building2,
  Camera,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  Clapperboard,
  ClipboardPaste,
  Copy,
  Cpu,
  CupSoda,
  Download,
  Ellipsis,
  Eye,
  FileText,
  Film,
  Folder,
  FolderHeart,
  FolderOpen,
  Funnel,
  Globe,
  Heart,
  HeartPulse,
  History,
  Image,
  Info,
  KeyRound,
  Layers,
  LayoutGrid,
  LayoutTemplate,
  Lightbulb,
  Link,
  ListChecks,
  ListOrdered,
  Loader,
  LoaderCircle,
  Lock,
  LogOut,
  Maximize2,
  MessageCircle,
  Mic,
  Minus,
  Moon,
  Palette,
  PenLine,
  Play,
  Plus,
  Quote,
  RefreshCw,
  Rocket,
  ScanFace,
  ScanSearch,
  Search,
  Settings,
  Share,
  Shield,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Sun,
  ThumbsUp,
  Trash2,
  Upload,
  User,
  Video,
  WandSparkles,
  X,
  Zap,
} from "lucide-react";

/** Lucide glyphs from `hongtai-mobile.pen` NA5 plus every icon used on unarchived screens. */
export const playbookGlyphs = {
  add: Plus,
  plus: Plus,
  remove: Minus,
  arrow_back: ChevronLeft,
  chevron_left: ChevronLeft,
  analytics: ScanSearch,
  scan_search: ScanSearch,
  aspect_ratio: Maximize2,
  expand: Maximize2,
  auto_awesome: WandSparkles,
  sparkle: WandSparkles,
  sparkles: WandSparkles,
  wand_sparkles: WandSparkles,
  bookmark: Bookmark,
  bolt: Zap,
  zap: Zap,
  business_center: Building2,
  camera: Camera,
  check_circle: CircleCheck,
  circle_check: CircleCheck,
  check_circle_2: CheckCircle2,
  chevron_right: ChevronRight,
  chevron_down: ChevronDown,
  chevron_up: ChevronUp,
  close: X,
  x: X,
  comment: MessageCircle,
  forum: MessageCircle,
  message_circle: MessageCircle,
  content_paste: ClipboardPaste,
  copy: Copy,
  download: Download,
  error: CircleAlert,
  face: User,
  person: User,
  user: User,
  file: FileText,
  file_text: FileText,
  filter: Funnel,
  folder: Folder,
  folder_open: FolderOpen,
  folder_special: FolderHeart,
  grid: LayoutGrid,
  health_cross: HeartPulse,
  heart: Heart,
  history: History,
  info: Info,
  key: KeyRound,
  keyboard_voice: Mic,
  voice: Mic,
  record_voice_over: Mic,
  language: Globe,
  layers: Layers,
  layout_template: LayoutTemplate,
  lightbulb: Lightbulb,
  link: Link,
  list: ListOrdered,
  list_ordered: ListOrdered,
  list_checks: ListChecks,
  lock: Lock,
  memory: Cpu,
  more_horiz: Ellipsis,
  movie: Film,
  film: Film,
  movie_edit: Clapperboard,
  clapperboard: Clapperboard,
  notifications: Bell,
  bell: Bell,
  pending: LoaderCircle,
  loader_circle: LoaderCircle,
  loader: Loader,
  scan_face: ScanFace,
  play: Play,
  publish: Share,
  share: Share,
  query_stats: ScanSearch,
  restaurant: CupSoda,
  cup_soda: CupSoda,
  rocket: Rocket,
  search: Search,
  self_improvement: WandSparkles,
  settings: Settings,
  sunny: Sun,
  sync: Loader,
  tune: SlidersHorizontal,
  update: RefreshCw,
  upload: Upload,
  upload_file: Image,
  image: Image,
  video_file: Video,
  video: Video,
  video_library: Film,
  visibility: Eye,
  eye: Eye,
  smart_toy: Bot,
  robot: Bot,
  logout: LogOut,
  palette: Palette,
  moon: Moon,
  trash_2: Trash2,
  shield: Shield,
  shield_alert: ShieldAlert,
  shield_check: ShieldCheck,
  quote: Quote,
  pen_line: PenLine,
  book_open: BookOpen,
  arrow_up: ArrowUp,
  thumbs_up: ThumbsUp,
  circle: Circle,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof playbookGlyphs;

export const spinningIconNames = ["pending", "sync", "update", "loader", "loader_circle"] as const satisfies readonly IconName[];

export interface PlaybookIconCell {
  readonly name: IconName;
  readonly label: string;
  readonly lucide: string;
}

/** NA5 图标 · Lucide · 描边风格 · 22px */
export const na5IconCells: readonly PlaybookIconCell[] = [
  { name: "sparkles", label: "智能", lucide: "wand-sparkles" },
  { name: "layers", label: "拆解", lucide: "layers" },
  { name: "clapperboard", label: "制作", lucide: "clapperboard" },
  { name: "layout_template", label: "模板", lucide: "layout-template" },
  { name: "settings", label: "设置", lucide: "settings" },
  { name: "scan_face", label: "观察", lucide: "scan-face" },
  { name: "link", label: "链接", lucide: "link" },
  { name: "video", label: "视频", lucide: "video" },
  { name: "plus", label: "创建", lucide: "plus" },
  { name: "chevron_left", label: "返回", lucide: "chevron-left" },
  { name: "chevron_right", label: "进入", lucide: "chevron-right" },
  { name: "share", label: "分享", lucide: "share" },
  { name: "folder", label: "素材", lucide: "folder" },
  { name: "camera", label: "拍摄", lucide: "camera" },
  { name: "image", label: "相册", lucide: "image" },
  { name: "bookmark", label: "收藏", lucide: "bookmark" },
  { name: "list_checks", label: "清单", lucide: "list-checks" },
  { name: "info", label: "提示", lucide: "info" },
  { name: "circle_check", label: "完成", lucide: "circle-check" },
  { name: "loader_circle", label: "进行中", lucide: "loader-circle" },
  { name: "bell", label: "通知", lucide: "bell" },
  { name: "user", label: "我的", lucide: "user" },
  { name: "lock", label: "密钥", lucide: "lock" },
  { name: "palette", label: "主题色", lucide: "palette" },
  { name: "moon", label: "深色", lucide: "moon" },
  { name: "trash_2", label: "清理", lucide: "trash-2" },
];

/** Icons used on unarchived screens that are not on the NA5 grid. */
export const screenIconCells: readonly PlaybookIconCell[] = [
  { name: "play", label: "播放", lucide: "play" },
  { name: "film", label: "影片", lucide: "film" },
  { name: "circle", label: "步骤待开始", lucide: "circle" },
  { name: "loader", label: "模块生成中", lucide: "loader" },
  { name: "scan_search", label: "概览", lucide: "scan-search" },
  { name: "zap", label: "开场钩子", lucide: "zap" },
  { name: "heart", label: "情绪驱动", lucide: "heart" },
  { name: "list_ordered", label: "内容结构", lucide: "list-ordered" },
  { name: "quote", label: "核心论点", lucide: "quote" },
  { name: "pen_line", label: "表达风格", lucide: "pen-line" },
  { name: "shield_alert", label: "风险边界", lucide: "shield-alert" },
  { name: "file_text", label: "证据", lucide: "file-text" },
  { name: "search", label: "搜索", lucide: "search" },
  { name: "shield", label: "隐私", lucide: "shield" },
  { name: "check_circle_2", label: "可见观察", lucide: "check-circle-2" },
  { name: "eye", label: "观察明细", lucide: "eye" },
  { name: "book_open", label: "日常参考", lucide: "book-open" },
  { name: "lightbulb", label: "日常建议", lucide: "lightbulb" },
  { name: "cup_soda", label: "清淡饮食", lucide: "cup-soda" },
  { name: "shield_check", label: "安全提醒", lucide: "shield-check" },
  { name: "arrow_up", label: "发送", lucide: "arrow-up" },
  { name: "message_circle", label: "追问", lucide: "message-circle" },
  { name: "x", label: "关闭", lucide: "x" },
  { name: "copy", label: "复制", lucide: "copy" },
  { name: "thumbs_up", label: "有用", lucide: "thumbs-up" },
  { name: "chevron_up", label: "收起", lucide: "chevron-up" },
];
