package com.hongtai.aiagent.bridge

/** Stable errors consumed by the shared TaskIssue presentation mapper. */
object NativeIssueCode {
  const val INVALID_ARGUMENT = "ERR_INVALID_ARGUMENT"
  const val LOCAL_DATA_UNAVAILABLE = "ERR_LOCAL_DATA_UNAVAILABLE"
  const val SECURE_STORAGE_UNAVAILABLE = "ERR_SECURE_STORAGE_UNAVAILABLE"
  const val PRIVATE_FILE_IMPORT_FAILED = "ERR_PRIVATE_FILE_IMPORT_FAILED"
  const val MEDIA_SELECTION_CANCELLED = "ERR_MEDIA_SELECTION_CANCELLED"
  const val MEDIA_SOURCE_MISSING = "ERR_MEDIA_SOURCE_MISSING"
  const val PHOTO_CAPTURE_LOST = "ERR_PHOTO_CAPTURE_LOST"
  const val PHOTO_RECOVERY_FAILED = "ERR_PHOTO_RECOVERY_FAILED"
  const val MEDIA_READ_FAILED = "ERR_MEDIA_READ_FAILED"
  const val IMAGE_TOO_LARGE = "ERR_IMAGE_TOO_LARGE"
  const val IMAGE_INVALID = "ERR_IMAGE_INVALID"
  const val MEDIA_PROBE_FAILED = "ERR_MEDIA_PROBE_FAILED"
  const val MEDIA_MERGE_FAILED = "ERR_MEDIA_MERGE_FAILED"
}
