pluginManagement {
  repositories {
    google()
    mavenCentral()
    gradlePluginPortal()
  }
}

dependencyResolutionManagement {
  // Capacitor and the community SQLCipher plugin declare their Android
  // repositories in their own Gradle modules, as generated by `cap sync`.
  repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
  repositories {
    google()
    mavenCentral()
  }
}

rootProject.name = "hongtai-ai-agent-android"
include(":app")
include(":capacitor-cordova-android-plugins")
project(":capacitor-cordova-android-plugins").projectDir = file("capacitor-cordova-android-plugins")

apply(from = "capacitor.settings.gradle")

// Keep the v8 Capacitor Community SQLite/SQLCipher implementation available to
// Kotlin only. It is deliberately not listed in Capacitor's JavaScript plugin
// allowlist, so `cap sync` cannot register `CapacitorSQLitePlugin` in the
// WebView bridge.
val communitySqliteNativeDir = file("../node_modules/@capacitor-community/sqlite/android")
check(communitySqliteNativeDir.isDirectory) {
  "Missing @capacitor-community/sqlite Android module. Run pnpm install before building Android."
}
include(":hongtai-community-sqlite-native")
project(":hongtai-community-sqlite-native").projectDir = communitySqliteNativeDir
